name: fit_app
description: A Flutter application for tracking macros and meals.

# This is the version number of your app.
version: 1.0.0+1

# The following section is specific to Flutter.
environment:
  sdk: ">=2.18.0 <3.0.0"

# Dependencies used in the project.
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  http: ^1.2.2
  google_generative_ai: ^0.4.6
  intl: ^0.19.0
  shared_preferences: ^2.2.2

# Development dependencies for testing, building, etc.
dev_dependencies:
  flutter_test:
    sdk: flutter

# The Flutter build system generates the .packages file,
# which defines the packages used by the project.
flutter:
  uses-material-design: true

  # This section is where you can specify assets to include in your application.
  # assets:
  #   - assets/images/  # Add your image assets directory here if you have any
